name: Saddles
main: me.sizzlemcgrizzle.saddles.Saddles
version: ${project.version}
api-version: 1.15
commands:
  saddles:
    description: Main plugin command group
permissions:
  saddles.admin:
    description: Default admin persmission
    default: op
  saddles.editor:
    description: Permission to edit mount properties
    default: op